// packages/react/src/components/content/ContentNavigationTree.tsx
import React from "react";
import PropTypes from "prop-types";
import {NavigationTreeLink} from "@mockline/themes";

export const MContentNavigationTree = ({ links, getClasses }: { links: NavigationTreeLink[]; getClasses: Function }) => {
  const isLinkActive = (link: any) => {
    if (typeof window !== "undefined") {
      return window.location.pathname.startsWith(link.path) || link.active === true;
    }
    return false;
  };

  return (
    <nav className={getClasses("root")}>{links?.length > 0 && (
      <ul className={getClasses("list")}>
        {links.map((link, index) => (
          <li key={index} className={getClasses("item", { active: isLinkActive(link), disabled: link.disabled })}>
            <a href={link.path} className={getClasses("link")}>
              {link.icon && <i className={getClasses("icon")}>{link.icon}</i>}
              <span className={getClasses("title")}>{link.title}</span>
              {link.badge && <span className={getClasses("badge")}>{link.badge}</span>}
            </a>
            {link.children?.length && link.children?.length > 0 && (
              <ul className={getClasses("list")}>
                {link.children.map((child, index) => (
                  <li key={index} className={getClasses("item", { active: isLinkActive(child), disabled: child.disabled })}>
                    <a href={child.path} className={getClasses("link")}>
                      {child.icon && <i className={getClasses("icon")}>{child.icon}</i>}
                      <span className={getClasses("title")}>{child.title}</span>
                      {child.badge && <span className={getClasses("badge")}>{child.badge}</span>}
                    </a>
                  </li>
                ))}
              </ul>
            )}
          </li>
        ))}
      </ul>
    )}</nav>
  );
};

MContentNavigationTree.propTypes = {
  links: PropTypes.arrayOf(
    PropTypes.shape({
      title: PropTypes.string,
      path: PropTypes.string.isRequired,
      active: PropTypes.bool,
      disabled: PropTypes.bool,
      icon: PropTypes.string,
      badge: PropTypes.string,
      children: PropTypes.arrayOf(
        PropTypes.shape({
          title: PropTypes.string.isRequired,
          path: PropTypes.string.isRequired,
          active: PropTypes.bool,
          disabled: PropTypes.bool,
          icon: PropTypes.string,
          badge: PropTypes.string,
        })
      ),
    })
  ).isRequired,
  getClasses: PropTypes.func.isRequired,
};

// packages/nuxt/src/runtime/components/content/ContentNavigationTree.vue
<script setup lang="ts">
import type { ContentNavigationItem } from '@nuxt/content'
import type { NavigationTreeProps, NavigationTreeLink } from '@mockline/themes'
import { useRoute } from '#imports'
import { useComponent } from '#mockline/utils/useComponent'

const props = defineProps<NavigationTreeProps & { links: ContentNavigationItem[] }>()

const route = useRoute()
const { getClasses } = useComponent('navigationTree', props)

const isLinkActive = (link: NavigationTreeLink): boolean => {
  return route.path.startsWith(link.path) || link.active === true
}
</script>

<template>
  <nav v-if="links?.length" :class="getClasses('root', props.class)">
    <template v-for="(link, index) in links" :key="index">
      <div>
        <h3 v-if="link.title" :class="getClasses('sectionTitle', props.titleClass)">
          {{ link.title }}
        </h3>
        <ul :class="getClasses('section')">
          <li v-for="(child, index_) in link.children" :key="index_">
            <NuxtLink
              :to="child.path"
              :class="getClasses('link', props.linkClass)"
              :data-active="isLinkActive(child)"
              :data-disabled="child.disabled"
              :aria-disabled="child.disabled"
            >
              <slot name="icon" :item="child" :active="isLinkActive(child)">
                <MIcon
                  v-if="child.icon"
                  :name="child.icon"
                  :class="getClasses('icon', props.iconClass)"
                />
              </slot>
              <slot name="title" :item="child" :active="isLinkActive(child)">
                <span>{{ child.title }}</span>
              </slot>

              <slot name="badge" :item="child" :active="isLinkActive(child)">
                <span v-if="child.badge" :class="getClasses('badge', props.badgeClass)">
                  {{ child.badge }}
                </span>
              </slot>
            </NuxtLink>
          </li>
        </ul>
      </div>
    </template>
  </nav>
</template>
