// packages/mockline/src/runtime/components/elements/Button.vue
<script setup lang="ts">
import { tv, type VariantProps } from 'tailwind-variants'
import { twMerge } from 'tailwind-merge'
import { computed } from 'vue'
import theme from '#build/mockline/button'

import { useComponentIcons, type UseComponentIconsProps } from '#mockline/composables/useComponentIcons'

const button = tv(theme)

type ButtonVariants = VariantProps<typeof button>

export type ButtonProps = {
  label?: string
  color?: ButtonVariants['color']
  variant?: ButtonVariants['variant']
  size?: ButtonVariants['size']
  rounded?: ButtonVariants['rounded']
  square?: boolean
  block?: boolean
  class?: string
  iconClass?: string
  labelClass?: string
} & UseComponentIconsProps

export type ButtonSlots = {
  leading(props?: NonNullable<unknown>): any
  default(props?: NonNullable<unknown>): any
  trailing(props?: NonNullable<unknown>): any
}

const props = defineProps<ButtonProps>()
const slots = defineSlots<ButtonSlots>()

const { isLeading, isTrailing, leadingIconName, trailingIconName } = useComponentIcons(props)

const ui = computed(() => tv({ extend: button })({
  ...props,
  square: props.square || (!slots.default && !props.label),
  leading: isLeading.value,
  trailing: isTrailing.value,
}))
</script>

<template>
  <component :is="'button'" :class="twMerge(ui.base(), props.class)">
    <slot name="leading">
      <MIcon
        v-if="isLeading && leadingIconName"
        :name="leadingIconName"
        :class="twMerge(ui.leadingIcon(), iconClass)"
      />
    </slot>

    <span v-if="label || !!slots.default" :class="twMerge(ui.label(), labelClass)">
      <slot>
        {{ label }}
      </slot>
    </span>

    <slot name="trailing">
      <MIcon
        v-if="isTrailing && trailingIconName"
        :name="trailingIconName"
        :class="twMerge(ui.trailingIcon(), iconClass)"
      />
    </slot>
  </component>
</template>

// packages/react/src/components/Button.tsx
import {FC, ReactNode} from "react";
import {Icon} from './Icon.tsx';
import {useComponent} from '../utils/useComponent.tsx';
import {useComponentIcons, UseComponentIconsProps} from '../composables/useComponentIcons.tsx';

type ButtonProps = {
    square?: boolean;
    label?: string;
    className?: string;
    iconClass?: string;
    labelClass?: string;
    children?: ReactNode;
    leading?: ReactNode;
    trailing?: ReactNode;
} & UseComponentIconsProps;

export const Button: FC<ButtonProps> = (props: ButtonProps) => {
    const {isLeading, isTrailing, leadingIconName, trailingIconName} = useComponentIcons(props)

    const componentProps = {
        ...props,
        square: props.square || (!props.children && !props.label),
        leading: isLeading,
        trailing: isTrailing,
    };

    const {getClasses} = useComponent("button", componentProps);

    return (
        <button className={getClasses("base", props.className)}>
            {(typeof props.leading != 'boolean' && props.leading) ||
                (isLeading && leadingIconName && (
                    <Icon name={leadingIconName} className={getClasses("leadingIcon", props.iconClass)}/>
                ))
            }

            {props.children || (props.label && (
                <span className={getClasses("label", props.labelClass)}>
                  {props.children || props.label}
                </span>
            ))}

            {(typeof props.trailing != 'boolean' && props.trailing) ||
                (isTrailing && trailingIconName && (
                    <Icon name={trailingIconName} className={getClasses("trailingIcon", props.iconClass)}/>
                ))}
        </button>
    );
};
