// packages/nuxt/src/runtime/components/Header.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useElementSize } from '@vueuse/core'
import type { HeaderProps, HeaderSlots } from '@mockline/themes'
import { useComponent } from '#mockline/utils/useComponent'

const props = defineProps<HeaderProps>()
const slots = defineSlots<HeaderSlots>()

const header = ref(null)
const { height } = useElementSize(header)

onMounted(() => {
  document.documentElement.style.setProperty('--header-height', `${height.value}px`)
})

const { getClasses } = useComponent('header', props)
</script>

<template>
  <component :is="'header'" ref="header" :class="getClasses('default', props.class)">
    <slot name="left" />
    <slot name="default" />
    <slot name="right" />
  </component>
</template>

// packages/react/src/components/Header.tsx
import { useRef, useEffect } from 'react';
import { useComponent } from '#mockline/utils/useComponent';
import type { HeaderProps, HeaderSlots } from '@mockline/themes'

type Properties = {
slots: HeaderSlots,
props: HeaderProps
}

export const Header = ({slots, props}: Properties) => {
  const headerRef = useRef<HTMLElement>(null);
  const { getClasses } = useComponent('header', props);

  useEffect(() => {
    if (headerRef.current) {
      const height = headerRef.current.offsetHeight;
      document.documentElement.style.setProperty('--header-height', `${height}px`);
    }
  }, []);

  return (
    <header ref={headerRef} className={getClasses('default', props.class)}>
      {slots.left}
      {slots.default}
      {slots.right}
    </header>
  );
};

export default Header;
