// packages/nuxt/src/runtime/components/Main.vue
<script setup lang="ts">
import { computed } from 'vue'
import { twMerge } from 'tailwind-merge'

export type MainProps = {
  class?: string
}

const props = defineProps<MainProps>()

const mainClasses = computed(() => twMerge(
  'h-full',
  props.class
))
</script>

<template>
  <main :class="mainClasses">
    <slot />
  </main>
</template>

// packages/react/src/components/Main.tsx
import React, { ReactNode, useMemo } from 'react'
import { twMerge } from 'tailwind-merge'

export type MainProps = {
  className?: string
  children?: ReactNode
}

export const Main: React.FC<MainProps> = ({ className, children }) => {
  const mainClasses = useMemo(() => {
    return twMerge('h-full', className)
  }, [className])

  return <main className={mainClasses}>{children}</main>
}
