// packages/nuxt/src/runtime/components/layout/PageBody.vue
<script setup lang="ts">
import { computed } from 'vue'
import { twMerge } from 'tailwind-merge'

export type PageBodyProps = {
  class?: string
  prose?: boolean
}

const props = withDefaults(defineProps<PageBodyProps>(), {
  prose: false
})

const pageBodyClasses = computed(() => twMerge(
  props.prose && 'prose prose-primary dark:prose-invert max-w-none',
  !props.prose && 'flex flex-col gap-4',
  props.class
))
</script>

<template>
  <div :class="pageBodyClasses">
    <slot />
  </div>
</template>

// packages/react/src/components/PageBody.tsx
import React, { ReactNode, useMemo } from 'react'
import { twMerge } from 'tailwind-merge'

export type PageBodyProps = {
  className?: string
  children?: ReactNode
}

export const PageBody: React.FC<PageBodyProps> = ({ className, children }) => {
  const mergedClasses = useMemo(() => twMerge('flex flex-col gap-4 w-full', className), [className])

  return <div className={mergedClasses}>{children}</div>
}
