// packages/react/src/components/Toasts.tsx
import React from 'react'
import { Toaster, ToasterProps } from 'react-hot-toast'

const VISIBLE_TOASTS_AMOUNT = 4
const VIEWPORT_OFFSET = '32px'
const TOAST_LIFETIME = 4000
const GAP = 14

export type ToastProps = ToasterProps & {
  className?: string
}

// const Toast: React.FC<ToastProps> = ({
//   className = '',
//   invert = false,
//   // TODO FIX WITH APP CONFIG
//   // position = appConfig.mockline?.toast?.position ?? 'top-center',
//   hotkey = ['altKey', 'KeyT'],
//   expand = false,
//   closeButton = false,
//   offset = VIEWPORT_OFFSET,
//   theme = 'light',
//   richColors = false,
//   // duration = appConfig.mockline?.toast?.duration ?? TOAST_LIFETIME,
//   visibleToasts = VISIBLE_TOASTS_AMOUNT,
//   toastOptions = {
//     style: {
//       color: 'var(--color-text-primary)',
//       borderColor: 'var(--color-border-primary)',
//       backgroundColor: 'var(--color-bg-secondary)',
//     },
//   },
//   dir = 'auto',
//   gap = GAP,
//   style = {},
// }) => {
//   return (
//     <Toaster
//       // position={position}
//       invert={invert}
//       hotkey={hotkey}
//       expand={expand}
//       closeButton={closeButton}
//       className={className}
//       offset={offset}
//       theme={theme}
//       richColors={richColors}
//       // duration={duration}
//       visibleToasts={visibleToasts}
//       toastOptions={toastOptions}
//       dir={dir}
//       gap={gap}
//       style={style}
//     />
//   )
// }

// export default Toast

// packages/mockline/src/runtime/components/overlays/Toasts.vue
<script setup lang="ts">
import { Toaster, type ToasterProps } from 'vue-sonner'
import appConfig from '#build/app.config'

// Default amount of visible toasts
const VISIBLE_TOASTS_AMOUNT = 4

// Viewport padding
const VIEWPORT_OFFSET = '32px'

// Default lifetime of a toasts (in ms)
const TOAST_LIFETIME = 4000

// Default gap between toasts
const GAP = 14

withDefaults(defineProps<ToasterProps>(), {
  invert: false,
  position: appConfig.mockline?.toast?.position ?? 'top-center',
  hotkey: () => ['altKey', 'KeyT'],
  expand: false,
  closeButton: false,
  className: '',
  offset: VIEWPORT_OFFSET,
  theme: 'light',
  richColors: false,
  duration: appConfig.mockline?.toast?.duration ?? TOAST_LIFETIME,
  visibleToasts: VISIBLE_TOASTS_AMOUNT,
  toastOptions: () => ({
    style: {
      borderColor: 'var(--color-canvas-5)',
      backgroundColor: 'var(--color-canvas-2)'
    }
  }),
  dir: 'auto',
  gap: GAP,
  style: () => ({}),
})
</script>

<template>
  <Toaster
    :position
    :invert
    :hotkey
    :expand
    :close-button
    :offset
    :style
    :theme="$colorMode.preference === 'dark' ? 'dark' : 'light'"
    :rich-colors
    :duration
    :visible-toasts
    :toast-options
    :dir
    :gap
  />
</template>
