// packages/react/src/components/Aside.tsx
import { twMerge } from 'tailwind-merge';
import { ReactNode } from 'react';

type AsideProps = {
  sticky?: boolean;
  className?: string;
  children?: ReactNode;
  bottom?: ReactNode;
}

export function Aside({
  sticky = true,
  className,
  children,
  bottom
}: AsideProps) {
  const asideClasses = twMerge(
    'overflow-y-auto',
    sticky && 'sticky top-[var(--header-height)]',
    className
  );

  return (
    <aside className={asideClasses}>
      <div className="relative">
        {children}
        {bottom}
      </div>
    </aside>
  );
}

// packages/nuxt/src/runtime/components/Aside.vue
<script setup lang="ts">
import { twMerge } from 'tailwind-merge'
import { computed } from 'vue'

type AsideProps = {
  sticky?: boolean
  class?: string
}

const props = withDefaults(defineProps<AsideProps>(), {
  sticky: true
})

const asideClasses = computed(() => twMerge(
  'overflow-y-auto',
  props.sticky && 'sticky top-[var(--header-height)]',
  props.class
))
</script>

<template>
  <aside :class="asideClasses">
    <div class="relative">
      <slot />

      <slot name="bottom" />
    </div>
  </aside>
</template>
