// packages/react/src/components/Button.tsx
import {FC, ReactNode} from "react";
import {Icon} from './Icon.tsx';
import {useComponent} from '../utils/useComponent.tsx';
import {useComponentIcons, UseComponentIconsProps} from '../composables/useComponentIcons.tsx';

type ButtonProps = {
    square?: boolean;
    label?: string;
    className?: string;
    iconClass?: string;
    labelClass?: string;
    children?: ReactNode;
    leading?: ReactNode;
    trailing?: ReactNode;
} & UseComponentIconsProps;

export const Button: FC<ButtonProps> = (props: ButtonProps) => {
    const {isLeading, isTrailing, leadingIconName, trailingIconName} = useComponentIcons(props)

    const componentProps = {
        ...props,
        square: props.square || (!props.children && !props.label),
        leading: isLeading,
        trailing: isTrailing,
    };

    const {getClasses} = useComponent("button", componentProps);

    return (
        <button className={getClasses("base", props.className)}>
            {(typeof props.leading != 'boolean' && props.leading) ||
                (isLeading && leadingIconName && (
                    <Icon name={leadingIconName} className={getClasses("leadingIcon", props.iconClass)}/>
                ))
            }

            {props.children || (props.label && (
                <span className={getClasses("label", props.labelClass)}>
                  {props.children || props.label}
                </span>
            ))}

            {(typeof props.trailing != 'boolean' && props.trailing) ||
                (isTrailing && trailingIconName && (
                    <Icon name={trailingIconName} className={getClasses("trailingIcon", props.iconClass)}/>
                ))}
        </button>
    );
};

// packages/nuxt/src/runtime/components/Button.vue
<script setup lang="ts">
import { computed } from 'vue'
import { type ButtonProps, type ButtonSlots } from '@mockline/themes'
import { useComponent } from '../utils/useComponent'
import { useComponentIcons, type UseComponentIconsProps } from '#mockline/composables/useComponentIcons'

const props = defineProps<ButtonProps & UseComponentIconsProps>()
const slots = defineSlots<ButtonSlots>()

const { isLeading, isTrailing, leadingIconName, trailingIconName } = useComponentIcons(props)

const componentProps = computed(() => {
  return {
    ...props,
    square: props.square || (!slots.default && !props.label),
    leading: isLeading.value,
    trailing: isTrailing.value,
  }
})

const { getClasses } = useComponent('button', componentProps)
</script>

<template>
  <component
    :is="'button'"
    :class="getClasses('base', props.class)"
  >
    <slot name="leading">
      <MIcon
        v-if="isLeading && leadingIconName"
        :name="leadingIconName"
        :class="getClasses('leadingIcon', iconClass)"
      />
    </slot>

    <span v-if="label || !!slots.default" :class="getClasses('label', labelClass)">
      <slot>
        {{ label }}
      </slot>
    </span>

    <slot name="trailing">
      <MIcon
        v-if="isTrailing && trailingIconName"
        :name="trailingIconName"
        :class="getClasses('trailingIcon', iconClass)"
      />
    </slot>
  </component>
</template>
