// packages/react/src/components/SideBar.tsx
import React, { useRef, useState, ReactNode } from 'react'
import type { SidebarProps, SidebarSlots } from '@mockline/themes'

const Sidebar: React.FC<SidebarProps & SidebarSlots> = ({
  minSize = 20,
  maxSize = 20,
  collapsedSize = 0,
  defaultSize = 20,
  className,
  header,
  footer,
  children
}) => {
  const [collapsed] = useState(false)
  const sidebarRef = useRef<HTMLElement | null>(null)

  return (
    <nav ref={sidebarRef} className={className}>
      <div className="flex flex-col gap-4">
        <div>{header}</div>
        <div>{children}</div>
      </div>
      <div>{footer}</div>
    </nav>
  )
}

export default Sidebar

// packages/nuxt/src/runtime/components/Sidebar.vue
<script setup lang="ts">
import type { SidebarProps, SidebarSlots } from '@mockline/themes'
import { computed, ref } from 'vue'
import { useComponent } from '#mockline/utils/useComponent'

const props = withDefaults(defineProps<SidebarProps>(), {
  minSize: 15,
  maxSize: 15,
  collapsedSize: 0,
  defaultSize: 20,
})

const slots = defineSlots<SidebarSlots>()

const collapsed = ref(false)

const sidebarRef = ref<HTMLElement | null>(null)

const componentProps = computed(() => {
  return {
    ...props,
  }
})

const { getClasses } = useComponent('sidebar', componentProps)
</script>

<template>
  <nav ref="sidebarRef" :class="getClasses('root', props.class)">
    <div class="flex flex-col gap-4">
      <div>
        <slot name="header" />
      </div>
      <div>
        <slot name="default" />
      </div>
    </div>
    <div>
      <slot name="footer" />
    </div>
  </nav>
</template>

<style scoped>

</style>
